# Generated by Django 3.0.1 on 2020-05-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200504_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_day',
        ),
        migrations.AddField(
            model_name='room',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
