# Generated by Django 3.0.1 on 2020-05-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('REJECTED', 'Rejected for use'), ('APPROVED', 'Approved for use')], default='PENDING', max_length=10),
        ),
    ]
