# Generated by Django 3.0.1 on 2020-05-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20200508_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='staff',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved for use')], default='PENDING', max_length=10),
        ),
    ]
