# Generated by Django 3.0.1 on 2020-05-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20200508_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
