# Generated by Django 3.0.4 on 2020-05-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_auto_20200508_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='roomID',
            new_name='room',
        ),
    ]
