# Generated by Django 3.0.4 on 2020-05-13 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_auto_20200509_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available_from',
            field=models.DateField(default=datetime.datetime.today, help_text='The date this room will be available for students'),
        ),
        migrations.AddField(
            model_name='room',
            name='available_to',
            field=models.DateField(blank=True, help_text='(Optional). Must be later than available from date. Null means room never expires', null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.IntegerField(help_text='(0-100)% off'),
        ),
    ]
